name: Thoughts on Reality
author: Erasmus Black
pygments: true
description: "This is my, Erasmus Black's, thoughts on reality."
url: http://yocer.github.io

public_key: "-----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBFHMNCsBEADPTwWZ6r4KPQnGD3E6ysL5jm2h+pbO0DEDKYb3wBVHJYyZOvCZ
Xyh+8h9VEUpD2t/CoIGTemnlJVdhihJFH/tuESl/CDMrdYSoPvs6PiGkyg0EFGgz
1Vb3Y/QI3WTN4HHtZaLyX/bWl4TWp/KTVTr1q/9UZPJtPq5IrnycT9ZRrDdVINbA
rg6CGczATIu/yxRY1HX2UObCfkjBsXLhIVoLVUrYtU1pfDbSSY3DBcEJpe3kB3+f
+AVWfJ+NLMie4ic/yI36J2YoqYe2rEENmY+eBa2xqw/x1tuzwn4VYvPxwjE595vU
rs/UrIdRMEDLuXVRiE07RGkPrRk6EsKMKPaNUZYBVCMYw+9u5jzH73tOD2fZN4gM
8uAHYKqt5gIGIDX/rO6104wVzs5MYB3LYNNKt5o3jhaUiwYnMnzlF8BILDzUAtxB
n9MjLllG7JRkSM9dwyR5/qY++ezWgZApLtGW5Zsp2qNBa04KW8+/mdS8X06W+j2V
DahKrBz2YGveUyUAbWnSUsED6ehrRtZiGwRCBOarh8V4Voh2CS8934dZT+xKHvQ5
/lx5qivRew+91ECH0tavlPZszX/W7aF05Om7Nhakqk15OxG15Yy0BBb/EwkN7FUV
8RsuuLO/bnRLaFq0qkFl1EHJAt0/GEEfOS069YWCmqjZV6oA/BGHOQljNQARAQAB
tDNFcmFzbXVzIEJsYWNrIChncGcga2V5KSA8ZXJhc211cy5ibGFja0BvdXRsb29r
LmNvbT6JAj0EEwEKACcFAlHMNCsCGy8FCQeGH4AFCwkIBwMFFQoJCAsFFgIDAQAC
HgECF4AACgkQEfWPPWo+A/3OGxAAwYV+cJzzW/d4YVKcpgyo2TrGzr3NxycgH8hq
8rHv78RC4aoX5yj86lJxcQgteSqjC+Z0MGGQ9aqlxmiT32cHxv4KulgzVPsy2WxN
V9AdOvr9NVga7Ozz6pwhDGosCAduKncO5Uz1pqZFLKgOLZ5DZxVBgCvQQKYx/+xZ
bUkxVkylAYZkFdQx7QwEsAlj/gKDrUZcdQu0cBsWRijsdSoRK+PCaDu0XY+SLtVH
CwO5F9UQR93AYMqJlRdiWpVYBKu+f2ygR6f8u10vlA6W6PFMbRULc2cazawJVnCX
GyXky00VnKLQlPTf7Oz6m9TXCmtwLY2J/Ub8bsgQSY7txGjWRjQgauTg62doU2PU
zTPO3J3quFIrPLu+FqgbTzbwYjl6Q0Bu0luZeVEkUd2IcdRTkkJ2kLHr4PgvABtQ
mliC1kL2VWidymnksnYuKeIhFoWiK/unoOC4p9J7rXN5qzzB8t2VwR70CitL7UFv
NEsm3ej1GSib9APxkjO280uFycn1L8uzxJPutAhhpoH4ZaMkotf5yJBpcVKhjAod
3TNw0NN0j4oerLBQTSLla6x42htop53JXFzOXDSDmkUsuhy3U+IkRmb9l9AQpBlY
pgOb4sqrkme0ZTVZDBtfZPuknmQgrTc1R8DkblDoMGDK9dUyH6eriSusL2RGpIEy
B1+i+Lu5Ag0EUcw0KwEQAOhvfJUhtaIjr7ico7J1KMwRUWDfWhVSzN0wt0d7wGN5
nss1tJT5GAXKEKGbJM5GxbmFkrP463wPvB2OBiI1vPooJuDq/1bumxBHE2Q2i/hy
+xlgX9roGT5zDkCfV7nqTmqZ0wNTTRzlqK9EL2yCdWosEzh0Jvm71cYtYMEgR4wN
H6aRP+R3vm+fzxYGIUXoihHGm+v/InOj/AZ//iX19pl8XnqhVwa0/xOHQu/sGJdu
jOM038jdF87DsJOigGPzj22ven13xuIxbnwXTYf/I/9+t6DUKiIkOV60uDGH2Se3
bWrYLZoExVlncHBXvfA50Tq5JzrThGFUFNx4IBQl/1wzTwpNCIFCrSjsGKcETyph
m8QhcoiWwMxAw1PxVbABHsjyOqdFQD2hgBTHL6zTlU0j2ab++qBQ8wfs6l7IYici
TKGdUFMpyaQJDoZ0B1ntIWNRUuMekN1geJMF4/32UiJkDetoTzzzjH6VeZB6hlJT
lWKFpLqO2xOTHFjNEUgywK/wtzG3xaxAgSruTTT+LLuzivmqRcL6ygCdql3D3MkY
ywe5AmWmTHphVpTgk4S48OeeOzWQ7EjvRtycOEpheUWBQv+wYG5vPCbOL4GC9xNQ
7SbhGgjcOHaPyemM7eE+BVWJwytPkbQisve2QzvJeLH4kHU54FHFy/eWE41gGU/T
ABEBAAGJBEQEGAEKAA8FAlHMNCsCGy4FCQeGH4ACKQkQEfWPPWo+A/3BXSAEGQEK
AAYFAlHMNCsACgkQA8ANrYYzaB4zghAAnyoWvjdtnZUIwi8q44pO+fJhC4F80UEe
9vGp4tjRLr0uTUjAEFwILpH92kko+kjuBk0tto6QiAuSswMbueHUkWAYTuhcv9hB
lTOn4Iu0pcwXggmsAzVjGgG08/XBUoBRYhtvD0TgeNZUN44CU1yvQfOPQwC5FLcY
2W+Wy6cA7dEis3lybPE7QZqEdJaVU1ScARQPKE2uZ/wiUAAwPKukIoxjYDdMqfTM
QZgJByBXPb+FBBUWNunxNBmvf5JBVeHm2PJvgdzk7IbApDf9GUJLFq2PeKDilmW9
GJ3eUcEzfXwjMgXeRuyIf6xPJMy02HtmvwDaoNh7KyivmIYDaQKsrMrtLi35UGQK
b/zi4HIlwDaD7PDTvR0yA/r83jUkyaV+kzcCb7fwq006/OXniZ9ONB2P7buev8hm
35xDEdovXrmfJq1CmZLOn6DOV5Sp0Pi8XGn4Psl4dR9/X+12UD57LbwGWIpW6JaK
OLhScT52fwI5ivJLfGzG+prdufSpM9gi+c3L5JboDk+Xoc4GaSDxPlcmRWZH4uH4
NaFei3OrA2sIqNmJwi2wHKhiqXFfHcQJcYaDBcFdNvIlcvDo0YmEmHhS25BjcGGb
KlEBwvijHcGs0FlNNoxgwsFgVKoaku1bMP1qsIfM/Plm5+y3qxaOBHUzmE6WPGhV
6oWQNDxj5eE9TBAAzgqZLzHc8hjzHFIF9P2Du5RVG9fkr0NxN9uBCcB8Enc5Mpq/
B5sSk0fXe0GegRzCcQFE2+PgX76RC4q97bg9BQ+DiX6nFJmeYNd76MX49d7Llsaf
QvpcMw4DIktiyyqD3QWB6PnceAvy03/SlLlq60wR3xM7DF++CcU00LiJeV6WJwu8
Jxo6Z/UDcTx5ew1U4Rw8wK77+oHFMKkMDkIHj7oRsYge9LBuiIh7sCsvc1xuJaid
lHdkQXPlbquOkllViKf4hpuhiRMZuMCgvCn1oFxltNplYPl28B5oOQ+uIAbUyYnr
7A5k/7hyRgo63Ybgje6PadQ4zVe0NLzX8WFwi2PTSk3YQEEWj1ohujwqgIG64nBg
L4dbG+Nl77sfnX6scM+wBzVCb1md1uctGfSvsrJXfqzVWOUrjBFNQ3tLl/INR9Ne
u8gxXldgkxT2wxzL/Bc8+a6ZbUhxDyphw6sXR8ZOTSl8PwPPzbyWxZDmVhu/I9Mq
FlKHkbOaM13KbU1UeaKarvtIujTjlPiINa8Ey5HPHliGiSXyMgFdtHj+RMSlsm+g
wAEOaGOKd9yncwgIPuYDPpDcLJhkDqTb50ck5VS4N8cxpQ/CkB/5FaFLTlMEB4YM
Uvm8kgIJYhCuY/qYNqrvI7gcLUjbm1i6Bt8/A6y65/YJr/pc4bJ9arztoIg=
=apM9
-----END PGP PUBLIC KEY BLOCK-----"